### ISSUE TITLE
stdout logging

### ISSUE THREAD

**Issue by jmajoor** [alexsilva/supervisor#11]
On Linux you can use /dev/stdout and /dev/stderr as log files for processes defined in the supervisor configuration file.

The supervisord process itself is writing to stdout, but I also want the output of the sub-processes to be on stdout.

Has an alternative for /dev/stdout been implemented?

**Comment by alexsilva** [comment]
For this case you need to write a log handler that writes to the stdout of the main process (supervisor).  This functionality does not currently exist.

**Comment by alexsilva** [comment]
You can try this plugin
https://github.com/coderanger/supervisor-stdout

**Comment by jmajoor** [comment]
There are some issues with the suggested package as it is no longer maintained and doesn't run on Python3. However when resolving those issues I seem to be running into the following in the dispatcher:
def handle_read_event(self):
        raise NotImplementedError

**Comment by jmajoor** [comment]
The supervisor-stdout package doesn't work properly with Python3, but some pull requests have fixed that. Using one of the python3 versions of supervisor-stdout I am still gettting the following:
can't concat str to bytes in handle_read_event|381

**Comment by alexsilva** [comment]
I will try to correct this problem.

**Comment by alexsilva** [comment]
I made the necessary changes that correct the problem `can't concat str to bytes in handle_read_event|381` but supervisor-stdout needs to be adjusted for this version of `supervisor + windows`

You can install and test with the command

`python -m pip install git+https://github.com/alexsilva/supervisor.git@windows -U`

[supervisor_stdout.zip](https://github.com/alexsilva/supervisor/files/4067792/supervisor_stdout.zip)

**Comment by jmajoor** [comment]
I tested it and it all seems to work. Thanks for the quick fix.
