### ISSUE TITLE
Custom service name?

### ISSUE THREAD

**Issue by billythekids** [alexsilva/supervisor#15]
Is there any argument for service's name that i can specify when i install new service ?

**Comment by alexsilva** [comment]
Not in the moment. It still needs to be done.

**Comment by alexsilva** [comment]
Working in progress [1d6a3b03](https://github.com/alexsilva/supervisor/commit/1d6a3b039131e176c4dd399469dc9eb43b612302)

**Comment by alexsilva** [comment]
You can test the new functionality by updating your version of the supervisor with the following command:

`python -m pip install git+https://github.com/alexsilva/supervisor.git@windows -U`

Once this is done, it is important to uninstall previous versions of the service:
`python -m supervisor.services remove`

Then just install the new service with the desired name:

`python -m supervisor.services install -c "{path}\supervisor.conf" -sn MyServiceName -sdn MyServiceDisplayName`

`-sn` - It is the name of the service
`-sdn` - It is the service's display name.
