### ISSUE TITLE
 Error comes out when I enter start command

### ISSUE THREAD

**Issue by creyeschaponan** [alexsilva/supervisor#16]
When I place the command:
python -m supervisor.services install -c supervisorord.conf
I get this error:
![image](https://user-images.githubusercontent.com/38223184/81125976-7ccf8180-8eff-11ea-87ca-48f111efe9df.png)

**Comment by alexsilva** [comment]
You need to pass the absolute path to the configuration file.
This path will be saved in the system registry and read when the service is executed.
