### ISSUE TITLE
Supervisor_twiddler ?

### ISSUE THREAD

**Issue by rchateauneu** [alexsilva/supervisor#19]
Is it compatible with the package supervisor_twiddler ? Thanks.

**Comment by alexsilva** [comment]
I believe so. Just testing to know.

**Comment by rchateauneu** [comment]
FYI, at the moment, this package always installs supervisor instead of supervisor-win if Windows. I created an issue here: https://github.com/mnaberez/supervisor_twiddler/issues/12

There is not much we can do in supervisor-win, except if is it merged into supervisor.
