### ISSUE TITLE
supervisor-win can not run in the foreground

### ISSUE THREAD

**Issue by zx2015** [alexsilva/supervisor#2]
I setup supervisor-win on Windows 10.
Use "C:\Python37\Scripts\supervisord --nodaemon" can not get it run in foreground.
One console windows pop up.

How to get it runs in foreground?
Or is it possible to register supervior-win to run as a services in windows?

**Comment by alexsilva** [comment]
Try install as service

`python -m supervisor.services install -c "{path}\supervisord.conf"`

ttps://github.com/alexsilva/supervisor/blob/master/supervisor/services.py

**Comment by alexsilva** [comment]
Just enter the command to run the supervisor

```
C:\Python37\Scripts\supervisord.exe --nodaemon -c "C:\supervisor\supervisord.conf"
```

If you do not run as expected then show the displayed error.
