### ISSUE TITLE
Travis CI and Windows

### ISSUE THREAD

**Issue by rchateauneu** [alexsilva/supervisor#20]
Travis CI has a Python distribution for Windows. Maybe it could be added to .travis.yml ?

**Comment by alexsilva** [comment]
If you want you can contribute to that.

**Comment by rchateauneu** [comment]
I forked your project and built it on Travis CI:
https://travis-ci.org/github/rchateauneu/supervisor

Apparently it needs pywin32 which is not installed.

Do you please have the same problem, or is the problem comes from my side ?

Thanks.

**Comment by alexsilva** [comment]
The windows branch is designed to work only with the Windows operating system. 
According to the execution, everything is correct, except for some access failures to environment variables.

https://travis-ci.org/github/rchateauneu/supervisor/jobs/716468236

**Comment by rchateauneu** [comment]
It builds: https://travis-ci.org/github/rchateauneu/supervisor/builds/717030395

**Comment by alexsilva** [comment]
If it is working, send pull requests.

**Comment by rchateauneu** [comment]
Done:
https://github.com/alexsilva/supervisor/pull/23

By the way, is there a method to start the supervisor as a plain subprocess and not as a service ? This question because it is not always possible to install it because of administrator rights. Thanks.

**Comment by alexsilva** [comment]
When you install the supervisor it creates scripts inside
`Python Install\Scripts`

If this directory is in the system path, just run in the terminal
Server: `supervisord.exe`
Cliente: `supervisorctl.exe`

**Comment by alexsilva** [comment]
travis is now in the readme, thanks. [readme](https://github.com/alexsilva/supervisor)
