### ISSUE TITLE
No modules found and No such file or directory

### ISSUE THREAD

**Issue by julemarts29** [alexsilva/supervisor#37]
So on my pc tried installing supervisor and when I tried to install the services using this command `python -m supervisor.services install -c {system-path}\\supervisord.conf` but it just gives me an error `No module named supervisor.services`, also tried for my Windows Server 2012 it also gives me an error `No such file or directory '{system-path}\\\\supervisrod.conf`. I even tried looking for solutions but wasn't able to find one, I looked up the Issues here and found a comment which was that he used cygwin to run supervisor.

**Comment by alexsilva** [comment]
This `{system-path}\\supervisrod.conf` is just an example.
You need to provide the correct location of the file.
For example if it is on disk `C:\\supervisor.cof` or `D:\\superivor.conf`

**Comment by julemarts29** [comment]
I got an error `"The Supervisor Pyv3.9 process monitor service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs."`

**Comment by alexsilva** [comment]
Is there nothing in the log files ?  Check in the same location as the supervisor.conf file or in the python.exe directory.

**Comment by julemarts29** [comment]
I found the log file it gives me this error
`2021-05-28 10:47:52,186 [INFO] supervisor config path: c:\supervisord.conf
2021-05-28 10:47:52,264 [ERROR] supervisor starting failed
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\supervisor\services.py", line 246, in main
    from supervisor import supervisord
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\supervisor\supervisord.py", line 41, in <module>
    from supervisor.options import ServerOptions
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\supervisor\options.py", line 9, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'`

**Comment by alexsilva** [comment]
Your installation is not correct. Try installing again with
`python.exe -m pip install supervisor-win -U`

**Comment by alexsilva** [comment]
Analyzing the problem better it seems that one version was installed over the other. 
The correct is to uninstall and reinstall completely.

`python.exe -m pip uninstall supervisor-win`
`python.exe -m pip uninstall supervisor`

# Supervisor for windows
`python.exe -m pip install supervisor-win`

**Comment by julemarts29** [comment]
It worked, do I need to edit the supervisord.conf?
I got this error after uninstalling the installed supervisor

`2021-05-29 13:55:19,876 [ERROR] Error: Format string '%(ENV_TMP)\\\\supervisord.log' for 'supervisord.logfile' is badly formatted: unsupported format character '\' (0x5c) at index 10
2021-05-29 13:55:19,877 [ERROR] For help, use C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\supervisor\services.py -h`

**Comment by alexsilva** [comment]
Formatting environment variable is incorrect. An "s" is missing.

http://supervisord.org/configuration.html#environment-variables

**Comment by julemarts29** [comment]
I got it to work! thank you!

**Comment by alexsilva** [comment]
Ok
