### ISSUE TITLE
Question: Installation on windows

### ISSUE THREAD

**Issue by ruiarodrigues** [alexsilva/supervisor#4]
Hi,

The installation information in the docs folder only refers to linux installation. How this should be installed in windows? What about installation without internet access?
Thanks

**Comment by alexsilva** [comment]
To install use pip:
`python -m pip install supervisor-win`

To install without internet, download zip
https://github.com/alexsilva/supervisor/archive/master.zip

Rename the file to `supervisor-win.zip` and put it on a pendrive.
`python -m pip install supervisor-win.zip`

**Comment by alexsilva** [comment]
It is also possible to install as a windows service:

`python -m supervisor.services install -c C:\\somepath\\supervisor.conf`

**Comment by ruiarodrigues** [comment]
Thanks. I will try..
