### ISSUE TITLE
Displaying process output in parent supervisor process

### ISSUE THREAD

**Issue by cheind** [alexsilva/supervisor#41]
Is it possible to display stdout/stderr of managed processes directly in supervisor console? I've see `redirect_stderr` for that purpose, but it does not work for me.

**Comment by alexsilva** [comment]
Use events for this.
http://supervisord.org/events.html#configuring-an-event-listener
https://github.com/alexsilva/supervisor/blob/windows/supervisor/scripts/sample_eventlistener.py

**Comment by cheind** [comment]
ok, thanks!
