### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by carmelom** [alexsilva/supervisor#43]
Currently the requirements pin `pywin32` to build 228 which is limited to python 3.9

**Comment by alexsilva** [comment]
The pywin32 version can be upgraded but it has been limited to avoid unexpected crashes. Have to test with new versions.

**Comment by alexsilva** [comment]
I understand why the version was limited. It's because this is the last version that supports python 2.7.

**Comment by atm84a** [comment]
So, are there any updates for the topic? Can we use different pywin32 versions for py2 and py3?

**Comment by hlovdal** [comment]
Version 228 is no longer available:

```bash
$ pip install --editable .
Obtaining file:///C:/github/supervisor
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in c:\github\supervisor\venv\lib\site-packages (from supervisor-win==4.6.1) (68.0.0)
INFO: pip is looking at multiple versions of supervisor-win to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pywin32==228 (from supervisor-win) (from versions: 302, 303, 304, 305, 306)
ERROR: No matching distribution found for pywin32==228
```

Python 2 was sunset years ago, it it time to remove all code that was related to that.

**Comment by alexsilva** [comment]
[Fix](https://github.com/alexsilva/supervisor/commit/89f907a6d9fca6f720a1f4a5ead95c202c7635d6)
