### ISSUE TITLE
Possible to execute it and not install it as a service?

### ISSUE THREAD

**Issue by klodoma** [alexsilva/supervisor#44]
I am looking to use this in Windows but only for a DEV environment, so I would like to execute it and not install it as a service. 
Is it possible? 

Thanks.

**Comment by alexsilva** [comment]
Usually the supervisor runs like this
`python -m supervisor.supervisord  -c {system-path}\\supervisord.conf`
The interactive mode (shell) is like this
`python -m supervisor.supervisorctl  -c {system-path}\\supervisord.conf`

http://supervisord.org/running.html#running-supervisord

A windows service, nothing more is a built-in supervisor.
https://github.com/alexsilva/supervisor/blob/windows/supervisor/services.py#L257

**Comment by klodoma** [comment]
Thank you!
