### ISSUE TITLE
Error: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by hysystem** [alexsilva/supervisor#47]
supervisord -c F:\code\dc-monitor\supervisord.conf
Error: 'gbk' codec can't decode byte 0xff in position 0: illegal multibyte sequence

**Comment by alexsilva** [comment]
Try converting your supervisor.conf file to utf-8.

**Comment by alexsilva** [comment]
@hysystem Do you have any additional information that would help resolve this? Log, config file, etc?

**Comment by hysystem** [comment]
> @hysystem Do you have any additional information that would help resolve this? Log, config file, etc?

The default generated file has been used and has been resolved
