### ISSUE TITLE
Question: environment for process

### ISSUE THREAD

**Issue by ruiarodrigues** [alexsilva/supervisor#6]
Hi,

The "supervisord" section has an environment attribute to customize the environment of supervisor and the child processes.
Do you know if it supports multiline?

Do you know any otherway to add env variables?
They can be a lot and put them in one line can be huge.

Thanks

**Comment by alexsilva** [comment]
It is possible to configure with multiple lines following the model below:

```
[supervisor]
environment=env_a=env_value_a,
            env_b=env_value_b
```

The parser reference follows:
https://docs.python.org/2/library/configparser.html
