### ISSUE TITLE
any limitation in program process ? 

### ISSUE THREAD

**Issue by haiyuanhe** [alexsilva/supervisor#8]
I  use the latest supervisor release  in 

**version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free**

and I startup the python daemon with supervisor.  found that the daemon print log so slow and nothing response(will block)  too.

I  check anything else in the  daemon , when I start then python daemon without supervisor  everything is work. but use supervisor  would be slow . 

Have you anything idea about this problem ? Anything limit in mulitprocess ? 

BTW the python daemon use  mulitprocess lib with python

**Comment by alexsilva** [comment]
The supervisor has a processing limiter. This limit is set by the [delaysecs](https://github.com/alexsilva/supervisor/blob/windows/supervisor/supervisord.py#L292)
Try setting a value smaller than default [0.2s](https://github.com/alexsilva/supervisor/blob/windows/supervisor/skel/sample.conf#L44)

For example:
```
[supervisord]
delaysecs=0.005
```
However this will increase the use of cpu by the supervisor.

It is also possible to configure [affinity](https://github.com/alexsilva/supervisor/blob/windows/supervisor/skel/sample.conf#L101) and [priorities](https://github.com/alexsilva/supervisor/blob/windows/supervisor/skel/sample.conf#L100) of processes.

But the priority and affinity options want the supervisor to be started by an administrator.

**Comment by haiyuanhe** [comment]
it  doesn't work .

```
[supervisor]
delaysecs=0.005

[program: xxx]
cpupriority=high
cpuaffinity=7

```

**Comment by haiyuanhe** [comment]
I  want to reproduce the problem with sample code  .  Write  a lot of logs in second , if the log delay print . Can we prove the  supervisor have throttle or  limit the  program in some where ?

**Comment by alexsilva** [comment]
The supervisor just runs the program with the subprocess module and reads stdout / stderr. 

Important points highlighted below:
[process.execute](https://github.com/alexsilva/supervisor/blob/windows/supervisor/process.py#L378)
[StreamAsync](https://github.com/alexsilva/supervisor/blob/windows/supervisor/helpers.py#L40)
